apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: local-cluster
  namespace: flux-system
spec:
  interval: 5m0s
  path: "./apps"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
